### ISSUE TITLE
Problem 8 needs removal or instructions need clarification

### ISSUE THREAD

**Issue by mikkelrd** [DevMountain/JS-Closures#5]
The line
`*Hint: Don't let this fool you. Break down what's really happening here.`
Should read something like:
`*Hint: Don't let this fool you. Break down what's really happening here. The length of the array is 6 (i.e. it's not infinite).`

**Comment by mikkelrd** [comment]
@JRobber Also, feedback from students is that it makes more sense if either:
1. there is an outer function that encloses the array so that there can be an enclosed counter var, or
2. we put it with callbacks, because that is what you get with the following (which passes the test):
```
var funcsArray = [
  function(){return 0},
  function(){return 1},
  function(){return 2},
  function(){return 3},
  function(){return 4},
  function(){return 5},
]
```

In other words, for this to really be applicable to closure, the student would have to come up with all this:
```
function scopeFactory(num){
 return function(){
   return num;
 }
}

var funcArray = [];
for(var i = 0; i <= 5; i++){
 funcArray.push(scopeFactory(i))
}
```
And the instructions don't really allude to that at all

**Comment by TomPridham** [comment]
I would suggest having the instructions and tests check for higher numbers than 6. I had a lot of students just hard code it instead of using a loop to populate it, which I don't think is really the intended solution even though it passes.

**Comment by r-walsh** [comment]
Problem removed in #15
