### ISSUE TITLE
Problem 7 (second to last one; i.e. the setTimeout one) needs better instructions

### ISSUE THREAD

**Issue by mikkelrd** [DevMountain/JS-Closures#9]
@JRobber While it is helpful to have the newScope function there as a hint, the vast majority of students still need hand-holding all the way through this one, myself included when I first encountered it. Maybe we should go as far as to point out that the anonymous function definition we are passing in on lines 203-205 is no sufficient and we need to harness a return value from newScope (which would have its own fixed closure) to get this to work.

**Comment by r-walsh** [comment]
Instructions updated in #15, we'll need to keep an eye on it though. This one is historically pretty difficult.
